title: 'Personal Blog'
remote_theme: zozobalogh0817/zocs@next
url: 'https://zozobalogh0817.github.io/zozobalogh0817/'
path: 'https://zozobalogh0817.github.io/zozobalogh0817'
settings: {
  home: "/",
  redirectTimeOut: 3,
  private: true,
  hasHeader: true,
  contactUs: { ownerName: "Balogh Zoltán Sándor", supportEmail: "zoltan.balogh@avolantis.net" }
}
