title: 'Personal Blog'
remote_theme: zozobalogh0817/wiki-theme
url: 'https://zozobalogh0817.github.io/zozobalogh0817/'
path: 'https://zozobalogh0817.github.io/zozobalogh0817'
settings: {
  home: "/",
  redirectTimeOut: 3,
  private: true,
  hasHeader: true,
  headerType: h,
  headerSize: 4,
  contactUs: { ownerName: "Balogh Zoltán Sándor", supportEmail: "zoltan.balogh@avolantis.net" }
}
