# Basic section
home: "/"
redirectTimeOut: 3
private: true
# END #

# Header section
hasHeader: true
# It can either h or display
headerType: h
# header size can be given (1 - 6) (1 is the biggest, 6 is the smallest in case headerType is display otherwise it reversed)
headerSize: 3
# END #

# Contact section
contactUs: { ownerName: "Balogh Zoltán Sándor", supportEmail: "zoltan.balogh@avolantis.net" }
# END #

# Developer tools section
devToolsEnabled: true
devToolsKey: cabata
# END #
